# hash:sha256:837b4a01585fd75c07553f2c38dd25520b40b33fa9ad083aa053f88ea1f27cb5
FROM registry.rc-uswest2.acmecorp.codeocean.dev/codeocean/mambaforge3:22.11.1-4-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /
