# hash:sha256:75f69a36908b4b139a7fcae77039088daeb671a0d8e89b49f4b9aee9b4790562
FROM registry.rc-upgrade-v-2.acmecorp.codeocean.dev/codeocean/mambaforge3:22.11.1-4-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /
